application: herb18
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: / 
  script: main.application
- url: .*
  script: main.application

libraries:
- name: jinja2
  version: latest
- name: markupsafe
  version: latest
