import logging

from google.appengine.api import memcache
from google.appengine.api import users
from google.appengine.ext import db


class Species(db.Model):
    Taxcd = db.StringProperty(default="")
    Syncd = db.StringProperty(default="")
    family_code = db.StringProperty(default="")
    genus = db.StringProperty(default="")
    species = db.StringProperty(default="")
    authority = db.StringProperty(default="")
    subsp = db.StringProperty(default="")
    variety = db.StringProperty(default="")
    forma = db.StringProperty(default="")
    subsp_auth = db.StringProperty(default="")
    var_auth = db.StringProperty(default="")
    forma_auth = db.StringProperty(default="")
    sub_family = db.StringProperty(default="")
    tribe = db.StringProperty(default="")
    common = db.StringProperty(default="")
    Wisc_found = db.StringProperty(default="")
    ssp = db.StringProperty(default="")
    var = db.StringProperty(default="")
    f = db.StringProperty(default="")
    hybrids = db.StringProperty(default="")
    status_code = db.StringProperty(default="")
    hide = db.StringProperty(default="")
    USDA = db.StringProperty(default="")
    COFC = db.StringProperty(default="")
    WETINDICAT = db.StringProperty(default="")
    FAM_NAME = db.StringProperty(default="")
    FAMILY = db.StringProperty(default="")
    GC = db.StringProperty(default="")
    FAMILY_COMMON = db.StringProperty(default="")
    SYNWisc_found = db.StringProperty(default="")
    SYNS_STATUS = db.StringProperty(default="")
    SYNV_STATUS = db.StringProperty(default="")
    SYNF_STATUS = db.StringProperty(default="")
    SYNHYBRIDS_STATUS = db.StringProperty(default="")
    SYNW_STATUS = db.StringProperty(default="")
    speciesweb_Taxcd = db.StringProperty(default="")
    Status = db.StringProperty(default="")
    Photo = db.StringProperty(default="")
    Photographer = db.StringProperty(default="")
    Thumbmaps = db.StringProperty(default="")
    Accgenus = db.StringProperty(default="")
    SORTOR = db.StringProperty(default="")
    Hand = db.StringProperty(default="")
    growth_habit_bck = db.StringProperty(default="")
    blooming_dt_bck = db.StringProperty(default="")
    origin_bck = db.StringProperty(default="")
    Thumbphoto = db.StringProperty(default="")
    date_time = db.StringProperty(default="")
    growth_habit = db.StringProperty(default="")
    blooming_dt = db.StringProperty(default="")
    origin = db.StringProperty(default="")
    Taxa = db.StringProperty(default="", multiline=True)
    #PKID = db.StringProperty(default="")
    #specimens = db.ListProperty(db.Key)

class Specimen(db.Model):
    ACCESSION = db.StringProperty(default="", multiline=True)
    TYPE = db.TextProperty(default="")
    COLLDATE = db.StringProperty(default="")
    FLOWER = db.StringProperty(default="")
    FRUIT = db.StringProperty(default="")
    STERILE = db.StringProperty(default="", multiline=True)
    OBJTYPE = db.StringProperty(default="", multiline=True)
    INST = db.StringProperty(default="")
    ANNCODE = db.StringProperty(default="")
    ANNDATE = db.StringProperty(default="", multiline=True)
    ANNSOURCE = db.StringProperty(default="")
    CITY = db.StringProperty(default="", multiline=True)
    SITENO = db.StringProperty(default="", multiline=True)
    CITYTYPE = db.StringProperty(default="")
    COLL2NAME = db.StringProperty(default="")
    COLL3NAME = db.StringProperty(default="")
    COLL1NAME = db.StringProperty(default="")
    COLLNO1 = db.StringProperty(default="")
    COLLEVENT = db.StringProperty(default="")
    TAXCD = db.StringProperty(default="")
    CFS = db.StringProperty(default="")
    CFV = db.StringProperty(default="")
    CFVariety = db.StringProperty(default="")
    HABITAT_MISC = db.TextProperty(default="")
    HABITAT = db.TextProperty(default="")
    LONGX = db.TextProperty(default="")
    LAT = db.StringProperty(default="")
    ELEV = db.StringProperty(default="")
    LLGENER = db.StringProperty(default="")
    LONG2 = db.StringProperty(default="")
    LAT2 = db.StringProperty(default="")
    LTDEC = db.StringProperty(default="")
    LGDEC = db.StringProperty(default="")
    NOWLOC = db.StringProperty(default="")
    LOAN = db.StringProperty(default="")
    PAGES = db.StringProperty(default="")
    ORIGCD = db.StringProperty(default="")
    PUBCD = db.StringProperty(default="")
    LITCIT = db.StringProperty(default="")
    PUBDATE = db.StringProperty(default="")
    PUBDATEA = db.StringProperty(default="", multiline=True)
    VERPERS = db.StringProperty(default="", multiline=True)
    VERDATE = db.StringProperty(default="", multiline=True)
    EX = db.StringProperty(default="")
    ARTICLE = db.StringProperty(default="")
    PREC = db.StringProperty(default="")
    STATEL = db.StringProperty(default="")
    COUNTY = db.StringProperty(default="")
    COUNTRY = db.StringProperty(default="")
    T1 = db.StringProperty(default="")
    R1 = db.StringProperty(default="")
    S1 = db.StringProperty(default="")
    NSEW_1 = db.StringProperty(default="")
    TRSGENER = db.StringProperty(default="", multiline=True)
    T2 = db.StringProperty(default="")
    R2 = db.StringProperty(default="", multiline=True)
    S2 = db.StringProperty(default="")
    NSEW_2 = db.StringProperty(default="")
    PLACE = db.StringProperty(default="", multiline=True)
    scan = db.StringProperty(default="", multiline=True)
    MAPFILE = db.StringProperty(default="")
    username = db.StringProperty(default="")
    date_time = db.StringProperty(default="")
    DTRS = db.StringProperty(default="", multiline=True)
    PKID = db.StringProperty(default="", multiline=True)
    species = db.ReferenceProperty(Species)
